/* Levels */
const OFF = 0;
const WARN = 1;
const ERROR = 2;

/* Options */
const ALWAYS = "always";

/* Config */
module.exports = {
  root: true,
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: ["./tsconfig.json"],
    sourceType: "module",
    tsconfigRootDir: __dirname,
  },
  plugins: ["@typescript-eslint", "jest"],
  settings: {
    react: {
      version: "detect",
    },
  },
  extends: [
    "airbnb-typescript",
    "airbnb/hooks",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
    "plugin:import/typescript",
    "plugin:jest/recommended",
    "prettier",
  ],
  env: {
    node: true,
    browser: true,
    jest: true,
    serviceworker: true,
  },
  ignorePatterns: ["build", "node_modules"],
  rules: {
    "@typescript-eslint/dot-notation": OFF,
    "@typescript-eslint/no-unsafe-call": OFF,
    "@typescript-eslint/ban-ts-comment": OFF,
    "@typescript-eslint/no-explicit-any": OFF,
    "@typescript-eslint/no-unsafe-return": OFF,
    "@typescript-eslint/no-unsafe-assignment": OFF,
    "@typescript-eslint/no-unsafe-member-access": OFF,
    "@typescript-eslint/explicit-module-boundary-types": OFF,
    "@typescript-eslint/restrict-template-expressions": OFF,
    "@typescript-eslint/no-use-before-define": OFF,
    "@typescript-eslint/require-await": ERROR,
    "@typescript-eslint/ban-types": [
      ERROR,
      {
        extendDefaults: true,
        types: {
          "{}": false,
        },
      },
    ],
    "@typescript-eslint/no-inferrable-types": WARN,
    "@typescript-eslint/no-floating-promises": ERROR,
    "@typescript-eslint/lines-between-class-members": WARN,
    "@typescript-eslint/no-throw-literal": ERROR,
    "@typescript-eslint/restrict-plus-operands": WARN,
    "@typescript-eslint/naming-convention": WARN,
    "@typescript-eslint/no-var-requires": OFF,
    "@typescript-eslint/unbound-method": OFF,
    "@typescript-eslint/no-shadow": OFF,
    eqeqeq: OFF,
    "default-case": ERROR,
    "import/order": ERROR,
    "import/no-unresolved": OFF,
    "import/no-extraneous-dependencies": WARN,
    "import/no-cycle": OFF,
    "import/prefer-default-export": OFF,
    "import/no-self-import": ERROR,
    "import/no-useless-path-segments": ERROR,
    "pescript-eslint/unbound-method": OFF,
    "no-unbound-method": OFF,
    "no-param-reassign": ERROR,
    "no-eval": OFF,
    "no-restricted-syntax": OFF,
    "no-shadow": OFF,
    "no-else-return": ERROR,
    "no-prototype-builtins": OFF,
    "no-console": ERROR,
    "no-underscore-dangle": OFF,
    "react/jsx-fragments": OFF,
    "react/jsx-filename-extension": OFF,
    "react/destructuring-assignment": OFF,
    "react/prop-types": OFF,
    "react/jsx-boolean-value": ERROR,
    "react/self-closing-comp": ERROR,
    "react-hooks/exhaustive-deps": OFF,
    "react-hooks/rules-of-hooks": ERROR,
    "react/jsx-props-no-spreading": OFF,
    "react/no-danger": OFF,
    "jest/no-identical-title": ERROR,
    "jest/no-mocks-import": WARN,
    "jsx-a11y/interactive-supports-focus": WARN,
    "jsx-a11y/click-events-have-key-events": WARN,
    "jsx-a11y/anchor-is-valid": WARN,
    "jsx-a11y/control-has-associated-label": WARN,
    "jsx-a11y/label-has-associated-control": WARN,
    "class-methods-use-this": WARN,
    "consistent-return": WARN,
    "prefer-template": ERROR,
    "prefer-const": ERROR,
    "array-callback-return": ERROR,
    "arrow-parens": [ERROR, ALWAYS],
    "react/require-default-props": [OFF],
    radix: [ERROR, ALWAYS],
  },
};
